# generated by datamodel-codegen:
#   filename:  example_from_docs.json
#   timestamp: 2023-04-12T14:31:10+00:00

from __future__ import annotations

from typing import List, Optional

from pydantic import BaseModel


class Author(BaseModel):
    name: Optional[str] = None
    id: Optional[int] = None


class CustomFields(BaseModel):
    defined_key: Optional[str] = None


class CustomFieldsListItem(BaseModel):
    name: Optional[str] = None
    value: Optional[str] = None


class FundingListItem(BaseModel):
    id: Optional[int] = None
    title: Optional[str] = None


class Timeline(BaseModel):
    firstOnline: Optional[str] = None
    publisherPublication: Optional[str] = None
    publisherAcceptance: Optional[str] = None


class Model(BaseModel):
    title: Optional[str] = None
    description: Optional[str] = None
    is_metadata_record: Optional[bool] = None
    metadata_reason: Optional[str] = None
    tags: Optional[List[str]] = None
    keywords: Optional[List[str]] = None
    references: Optional[List[str]] = None
    categories: Optional[List[int]] = None
    categories_by_source_id: Optional[List[str]] = None
    authors: Optional[List[Author]] = None
    custom_fields: Optional[CustomFields] = None
    custom_fields_list: Optional[List[CustomFieldsListItem]] = None
    defined_type: Optional[str] = None
    funding: Optional[str] = None
    funding_list: Optional[List[FundingListItem]] = None
    license: Optional[int] = None
    doi: Optional[str] = None
    handle: Optional[str] = None
    resource_doi: Optional[str] = None
    resource_title: Optional[str] = None
    timeline: Optional[Timeline] = None
    group_id: Optional[int] = None
