# generated by datamodel-codegen:
#   filename:  example_article.json
#   timestamp: 2023-03-29T19:50:20+00:00

from __future__ import annotations

from typing import Any, List, Optional

from pydantic import BaseModel


class File(BaseModel):
    id: Optional[int] = None
    name: Optional[str] = None
    size: Optional[int] = None
    is_link_only: Optional[bool] = None
    download_url: Optional[str] = None
    supplied_md5: Optional[str] = None
    computed_md5: Optional[str] = None


class Author(BaseModel):
    id: Optional[int] = None
    full_name: Optional[str] = None
    is_active: Optional[bool] = None
    url_name: Optional[str] = None
    orcid_id: Optional[str] = None


class FundingListItem(BaseModel):
    id: Optional[int] = None
    title: Optional[str] = None
    grant_code: Optional[str] = None
    funder_name: Optional[Any] = None
    is_user_defined: Optional[int] = None


class License(BaseModel):
    value: Optional[int] = None
    name: Optional[str] = None
    url: Optional[str] = None


class Category(BaseModel):
    id: Optional[int] = None
    title: Optional[str] = None
    parent_id: Optional[int] = None
    path: Optional[str] = None
    source_id: Optional[str] = None
    taxonomy_id: Optional[int] = None


class Timeline(BaseModel):
    posted: Optional[str] = None
    firstOnline: Optional[str] = None


class Model(BaseModel):
    files: Optional[List[File]] = None
    custom_fields: Optional[List] = None
    authors: Optional[List[Author]] = None
    figshare_url: Optional[str] = None
    description: Optional[str] = None
    funding: Optional[str] = None
    funding_list: Optional[List[FundingListItem]] = None
    version: Optional[int] = None
    status: Optional[str] = None
    size: Optional[int] = None
    created_date: Optional[str] = None
    modified_date: Optional[str] = None
    is_public: Optional[bool] = None
    is_confidential: Optional[bool] = None
    is_metadata_record: Optional[bool] = None
    confidential_reason: Optional[str] = None
    metadata_reason: Optional[str] = None
    license: Optional[License] = None
    tags: Optional[List[str]] = None
    categories: Optional[List[Category]] = None
    references: Optional[List] = None
    has_linked_file: Optional[bool] = None
    citation: Optional[str] = None
    is_embargoed: Optional[bool] = None
    embargo_date: Optional[Any] = None
    embargo_type: Optional[str] = None
    embargo_title: Optional[str] = None
    embargo_reason: Optional[str] = None
    embargo_options: Optional[List] = None
    id: Optional[int] = None
    title: Optional[str] = None
    doi: Optional[str] = None
    handle: Optional[str] = None
    url: Optional[str] = None
    published_date: Optional[str] = None
    thumb: Optional[str] = None
    defined_type: Optional[int] = None
    defined_type_name: Optional[str] = None
    group_id: Optional[int] = None
    url_private_api: Optional[str] = None
    url_public_api: Optional[str] = None
    url_private_html: Optional[str] = None
    url_public_html: Optional[str] = None
    timeline: Optional[Timeline] = None
    resource_title: Optional[Any] = None
    resource_doi: Optional[Any] = None
